### 访问服务端GET接口，测试服务端是否能够正常提供服务
GET http://127.0.0.1:9001/pay/get?id=1

### 访问服务端GET接口，测试服务端是否能够正常提供服务
GET http://127.0.0.1:9001/pay/info

### 访问服务端GET接口，测试服务端是否能够正常提供服务
GET http://127.0.0.1:9002/pay/info

### 测试通过RestTemplate进行负载均衡
GET http://127.0.0.1:8001/restTemplate/info

### 测试Nacos作为配置中心获取配置信息，并且测试可以动态刷新
GET http://127.0.0.1:3377/get/nacos/config

### sentinel 测试接口A
GET http://localhost:9001/flow/limit/testA

### sentinel 测试接口B
GET http://localhost:9001/flow/limit/testB

### sentinel 测试接口F -- sleep1
GET http://localhost:9001/flow/limit/testF

### sentinel 测试接口G -- 抛出异常
GET http://localhost:9001/flow/limit/testG

### sentinel 按照 @SentinelResource 注解进行测试
GET http://127.0.0.1:9001/sentinel/resource/byResource?id=2

### sentinel 热点限流
GET http://127.0.0.1:9001/hotkey/test?goods=phone&id=3

### sentinel 热点限流 - 参数例外项额外限流控制
GET http://127.0.0.1:9001/hotkey/test?goods=book&id=3

### sentinel 非热点参数不限流
GET http://127.0.0.1:9001/hotkey/test?id=3

### 授权规则测试 - 白名单
GET http://127.0.0.1:9001/grant/grant?serverName=test

### 授权规则测试 - 黑名单
GET http://127.0.0.1:9001/grant/grant?serverName=test3