# ------ order openfeign ----
### 通过Feign接口查询
GET http://127.0.0.1:8002/order/feign/get?id=2

<> 2026-01-17T221021.200.json
<> 2026-01-17T220958.400.json

### 模拟依旧支持LB的能力

GET http://127.0.0.1:8002/order/feign/consul

<> 2026-01-17T221048-1.200.json
<> 2026-01-17T221048.200.json
<> 2026-01-17T221045.200.json

### 使用OpenFeign新增一条记录
POST http://127.0.0.1:8002/order/feign/add
Content-Type: application/json

{
  "payNo": "pay17203623",
  "orderNo": "6544bafb42d2",
  "amount": 100.30,
  "userId": 2
}

### 使用openfeign查询全部数据
GET http://127.0.0.1:8002/order/feign/all

### 模拟断路器接口正常请求
GET http://127.0.0.1:8002/order/circuit/test?id=1

### 模拟断路器接口异常请求，可以看到服务降级
GET http://127.0.0.1:8002/order/circuit/test?id=-4

### 模拟断路器接口慢调用请求，可以看到服务降级
GET http://127.0.0.1:8002/order/circuit/test?id=9999

### 模拟仓壁隔离接口正常请求
GET http://127.0.0.1:8002/order/circuit/bulkhead/semaphore?id=3

### 模拟仓壁隔离接口异常请求
GET http://127.0.0.1:8002/order/circuit/bulkhead/semaphore?id=9999


### 模拟仓壁隔离接口正常请求-ThreadPool
GET http://127.0.0.1:8002/order/circuit/bulkhead/threadPool?id=3

### 模拟仓壁隔离接口异常请求-ThreadPool
GET http://127.0.0.1:8002/order/circuit/bulkhead/threadPool?id=9999

### 模拟限流请求
GET http://127.0.0.1:8002/order/circuit/rateLimit?id=1

### 链路跟踪测试
GET http://127.0.0.1:8002/order/feign/micrometer/hello?id=1

### 网关测试服务端get接口
GET http://127.0.0.1:9001/gateway/get?id=1

### 网关测试服务端info接口
GET http://127.0.0.1:9001/gateway/info

### 访问网关测试服务端get接口
GET http://127.0.0.1:9527/gateway/get?id=1

### 访问网关测试服务端info接口
GET http://127.0.0.1:9527/gateway/info?userType=diamond
Cookie: sender=wander
X-Request-Id: 123
Host: nas.wander.com

### 访问网关测试服务端filter接口
GET http://127.0.0.1:9527/gateway/filter

### 访问网关测试服务端filter接口，测试携带参数
GET http://127.0.0.1:9527/gateway/filter?customerId=123&customerName=zs

### 通过consumer端尝试通过OpenFeign访问接口
GET http://127.0.0.1:8002/gateway/info

### 系统外部服务通过feign接口访问时，应该通过网关
GET http://127.0.0.1:9901/out/gateway/info