server:
  port: 8002
spring:
  application:
    name: cloud-consumer-openfeign

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
# 全局OpenFeign超时配置
    openfeign:
      client:
        config:
          default: # 对于全部的进行控制，修改为4s更容易观察现象
            connectTimeout: 30000
            readTimeout: 30000
      # 使用httpclient5
      httpclient:
        hc5:
          enabled: true
      # 开启压缩
      compression:
        request:
          enabled: true
          mime-types: text/xml, application/xml, application/json # 触发数据压缩的类型
          min-request-size: 2048 # 最小触发压缩的大小
        response:
          enabled: true
     # 开启断路器相关能力，开启分组能力
      circuitbreaker:
        enabled: true
#        group:
#          enabled: true

# 基于 count_based 的配置
#resilience4j:
#  circuitbreaker:
#    configs:
#      default: # 默认配置
#        failure-rate-threshold: 50
#        sliding-window-type: count_based
#        sliding-window-size: 6
#        minimum-number-of-calls: 6
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state:
#          seconds: 5
#        permitted-number-of-calls-in-half-open-state: 2
#        record-exceptions:
#          - java.lang.Exception

# 基于time_based 配置
resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 2
        limit-refresh-period: 1s
        timeout-duration: 1
    instances:
      cloud-provider-payment:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 10s # timelimiter默认限制远程1s，超过1s就会超时异常，配置了降级就走降级逻辑
    instances:
      cloud-provider-payment:
        base-config: default
  thread-pool-bulkhead:
    configs:
      default:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
    instances:
      cloud-provider-payment:
        base-config: default
      backendB:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
#  bulkhead:
#    configs:
#      default:
#        max-concurrent-calls: 2
#        max-wait-duration: 1s
#    instances:
#      cloud-provider-payment:
#        base-config: default
#      backendB:
#        max-wait-duration: 10ms
#        max-concurrent-calls: 20
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 2s
        slow-call-rate-threshold: 30
        sliding-window-type: time_based
        sliding-window-size: 2
        minimum-number-of-calls: 2
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state:
          seconds: 5
        record-exceptions:
          - java.lang.Exception
    instances:
      cloud-provider-payment:
        base-config: default

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      # 采样率(默认为0.1,就是10次会有1次被采样)
      probability: 1.0

# 开启打印OpenFeign接口的日志
logging:
  level:
    com.wander.apis.PaymentFeignAPI: debug