server:
  port: 8002
spring:
  application:
    name: cloud-consumer-openfeign

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
# 全局OpenFeign超时配置
    openfeign:
      client:
        config:
          default: # 对于全部的进行控制，修改为4s更容易观察现象
            connectTimeout: 4000
            readTimeout: 4000
      # 使用httpclient5
      httpclient:
        hc5:
          enabled: true