server:
  port: 9001

spring:
  application:
    name: cloud-alibaba-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/db2023?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858 # dashboard控制台地址
        port: 8719 # 默认8791端口，如果被占用，会从8791依次+1扫描，直到找到未被占用的接口
      web-context-unify: false # 默认为true，上下文是否是同一个链路，修改为false认为controller对service是不同链路

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wander.entity
  configuration:
    map-underscore-to-camel-case: true
