server:
  port: 9527

spring:
  application:
    name: cloud-gateway # 以微服务注册进入到consul中
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

    # 网关通过 shortcut 的方式进行配置
    gateway:
      routes:
        - id: pay_get # 路由的唯一ID
          # uri: "http://localhost:9001" # 路由匹配后提供服务的地址
          uri:
            lb://cloud-provider-payment # 通过微服务名字来进行匹配
          predicates:
            - Path=/gateway/get/** # 断言，路径匹配相对应的路由
        - id: pay_info
          # uri: "http://localhost:9001"
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/gateway/info
            - After=2026-01-24T22:42:10.345714+08:00[Asia/Shanghai]
            - Cookie=sender, wander
            - Header=X-Request-Id, \d+
            - Host=*.wander.com
            - My=diamond
        - id: pay_filter
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/gateway/filter
          filters:
            - AddRequestHeader=X-Request-wander1,wander1
            - AddRequestHeader=X-Request-wander2,wander2
            - RemoveRequestHeader=user-agent
            - AddRequestParameter=customerId,9527
            - RemoveRequestParameter=customerName
            - AddResponseHeader=X-Response-wander2, wander2value
            - SetResponseHeader=Date,2009-11-11
            - RemoveResponseHeader=X-Response-wander